### PR TITLE
Updating GsfProxy versions and enabling direct ROM build

### PR DESCRIPTION
**Pull request by chris42**
Similar to FakeStore I updated the versions according to the rest of the project and adapted a few things to allow for direct build within a ROM. I tested this with a Sony AOSP build and was using it for a while without errors.

Would be happy to have this included in the microg repository (e.g. as version 0.2?), as I then can close the fork.

Regular build should be unaffected, at least it is in my setup.

### CODE REVIEW

**Comment by ale5000-git** [comment]
@chris42: Hi,
could you please avoid bumping minSdkVersion?

**Comment by chris42** [comment]
@ale5000-git 
Not sure why I changed it here. Tested, it works with 9 as well.

**Comment by ale5000-git** [comment]
Thanks.

**Comment by chris42** [comment]
Will close this and update a new one after Tests for Pie

**Pull request closed without merging**
